In [5]:
import pandas as pd
import numpy as np

from sklearn.preprocessing import StandardScaler, OrdinalEncoder

# Prepare Data

In [9]:
#Solution
%load_ext autoreload
%autoreload 2

In [10]:
df_raw_beer = pd.read_csv('../data/raw/beer_reviews.csv')

In [11]:
df_cleaned = df_raw_beer.copy()

### Transform numerical columns

In [12]:
num_cols = ['review_aroma', 'review_appearance', 'review_palate', 'review_taste', 'beer_abv']

sc = StandardScaler()

df_cleaned[num_cols] = sc.fit_transform(df_cleaned[num_cols])

In [13]:
df_cleaned

,brewery_id,brewery_name,review_time,review_overall,review_aroma,review_appearance,review_profilename,beer_style,review_palate,review_taste,beer_name,beer_abv,beer_beerid
0,10325,Vecchio Birraio,1234817823,1.5,-2.487952,-2.177663,stcules,Hefeweizen,-3.288833,-3.132454,Sausa Weizen,-0.879382,47986
1,10325,Vecchio Birraio,1235915097,3.0,-1.771225,-1.366096,stcules,English Strong Ale,-1.090123,-1.083188,Red Moon,-0.362703,48213
2,10325,Vecchio Birraio,1235916604,3.0,-1.771225,-1.366096,stcules,Foreign / Export Stout,-1.090123,-1.083188,Black Horse Black Beer,-0.233533,48215
3,10325,Vecchio Birraio,1234725145,3.0,-1.054499,-0.554530,stcules,German Pilsener,-1.823026,-1.083188,Sausa Pils,-0.879382,47969
4,1075,Caldera Brewing Company,1293735206,4.0,1.095679,0.257037,johnmichaelsen,American Double / Imperial IPA,0.375684,0.966078,Cauldron DIPA,0.283146,64883
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1586609,14359,The Defiant Brewing Company,1162684892,5.0,0.378953,-0.554530,maddogruss,Pumpkin Ale,0.375684,0.282989,The Horseman's Ale,-0.793269,33061
1586610,14359,The Defiant Brewing Company,1161048566,4.0,1.812405,-2.177663,yelterdow,Pumpkin Ale,-2.555929,0.282989,The Horseman's Ale,-0.793269,33061
1586611,14359,The Defiant Brewing Company,1160702513,4.5,-0.337773,-1.366096,TongoRad,Pumpkin Ale,-0.357219,0.282989,The Horseman's Ale,-0.793269,33061
1586612,14359,The Defiant Brewing Company,1160023044,4.0,1.095679,1.068603,dherling,Pumpkin Ale,1.108588,0.966078,The Horseman's Ale,-0.793269,33061
1586613,14359,The Defiant Brewing Company,1160005319,5.0,1.095679,1.068603,cbl2,Pumpkin Ale,1.108588,0.966078,The Horseman's Ale,-0.793269,33061

In [8]:
# Convert the column beer_style as integer
df_cleaned['beer_style'] = df_cleaned['beer_style'].astype(int)

ValueError: invalid literal for int() with base 10: 'Hefeweizen'